### ISSUE TITLE
Updates moves document to top of the Confluence space

### ISSUE THREAD

**Issue by telnetmaster** [govdelivery/sync_readme#3]
If I create a document in Confluence under `My new space -> How-to's` and use `sync_readme` to update that document, it moves it to the top space under `My new space`.

These are my settings in `.sync_readme.yml`:

```
how-to-do-task-A:
  url: https://confluence.example.com
  page_id: 12345
  filename: how-to-do-task-A.md
  notice: <h4>This wiki page is being controlled through git</h4>
```
